### ISSUE TITLE
zk-rollups link appears to have typo

### ISSUE THREAD

**Issue by dr-frmr** [kinode-dao/kinode-site#1]
https://github.com/uqbar-dao/phonebook/blob/f2410a10314779205f921326c2ab3bc855a9b100/src/views/Home.tsx#L69

https://uqbar.network/developers/zero-knowledge
It also appears that the corrected link doesn't lead anywhere -- should maybe link to a docs page?

**Comment by 0x70b1a5** [comment]
Right... we took down the old website, so we lost the ability to link
to it.  That page used to have the content that's in this file.
https://github.com/uqbar-dao/site/blob/master/src/locale/zero-knowlegde.ts

**Comment by 0x70b1a5** [comment]
Second best, I think, is linking to an existing blog post. https://uqbarnetwork.medium.com/zk-execution-and-uqbar-a8f49784155e
